export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CLEAR_ERRORS = 'AUTH_CLEAR_ERRORS';
export const AUTH_LOAD_USER_SUCCESS = 'AUTH_LOAD_USER_SUCCESS';

export const GET_PRICE_LIST = 'GET_PRICE_LIST';
export const PRICE_LIST_ERROR = 'PRICE_LIST_ERROR';



