export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CLEAR_ERRORS = 'AUTH_CLEAR_ERRORS';
export const AUTH_LOAD_USER_SUCCESS = 'AUTH_LOAD_USER_SUCCESS';

export const GET_PRICE_LIST = 'GET_PRICE_LIST';
export const GET_MY_ORDERS = 'GET_MY_ORDERS';
export const SET_CURRENT_ORDER = 'SET_CURRENT_ORDER';
export const CLEAR_CURRENT_ORDER = 'CLEAR_CURRENT_ORDER';
export const DELETE_ORDER_ITEM = 'DELETE_ORDER_ITEM';
export const UPDATE_ORDER = 'UPDATE_ORDER';

export const ORDERS_ERROR = 'ORDERS_ERROR';






